# Generated by Django 5.0 on 2025-12-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="user",
        ),
        migrations.AddField(
            model_name="reservation",
            name="user_name",
            field=models.CharField(default="guest", max_length=255),
        ),
    ]
