# Generated by Django 5.0 on 2025-12-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_remove_reservation_user_reservation_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="purpose",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(default="booked", max_length=20),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user_name",
            field=models.CharField(max_length=255),
        ),
    ]
